language: ruby
sudo: false
cache: bundler
rvm:
- 2.1
script: bundle exec middleman build
deploy:
- provider: s3
  access_key_id: AKIAJRN7WFNBVEFDWQTQ
  secret_access_key:
    secure: h4mmzHWY15/bbwJCeIrfQAQ5yfKin7Mp/OmJmSnqyQzNg8Q5g6jBTikZOdO7Db8PbSIXPrpPHf7Y6dKt55yfoLCJXH8icJfstkD0ZTVTh9A2GC7JmcdBwWcRYwRbcnRU0qeMHEOKQRnsX4tzz8p8T8ZcyT9DdXK7n7QCRjMc9ELa54LpKjOO/+uhjPwdhmFclTHgUo46x2tzGsoGWbiClpMoTLFfLITmDl/6f9icWiZE8HPpqWuWXQHOfVyokj77ue0ipBEeU1HHGA/EIQvzW80CMjHXvSpTzibTf6dAVAj+3vgOSRGa40d8L8ye0PoPKMW7fcRV7TcQp/CZMLOJzcnG8pFUw1DOsjzCr28Basd9JfSbqWQpvM/K65m1e4nbURXXHkYuCyrZ8duGZ75XiZGzLZmNNsbdmUBgR9ll6qOj8UloHAz2x7tI2iho4hxYczVEjXsq+cD35F96/XEGK/5MHF9RddGnSAoTVjd1/Kz49OsoZQAqQFsGgpttKLeMwAIRcBROEMQxpAlrqYO+KFXmU4mSzQA3oNmMfzzy1vmnNpFsZgYTx7DWikwSEv7GODAdQPUHPYX/2JEaOXIrqom9UPDTDRGq+Ln6Vruqy++LmwOtYaZ/DaM1scEdxS30Etsfz0DwZ/GX5Rw2J1eG9yNc/mGYw2BDpm3WnGMBzvQ=
  bucket: beta.lgbtq.fm
  local-dir: build
  skip_cleanup: true
  on:
    all_branches: true
- provider: s3
  access_key_id: AKIAJRN7WFNBVEFDWQTQ
  secret_access_key:
    secure: h4mmzHWY15/bbwJCeIrfQAQ5yfKin7Mp/OmJmSnqyQzNg8Q5g6jBTikZOdO7Db8PbSIXPrpPHf7Y6dKt55yfoLCJXH8icJfstkD0ZTVTh9A2GC7JmcdBwWcRYwRbcnRU0qeMHEOKQRnsX4tzz8p8T8ZcyT9DdXK7n7QCRjMc9ELa54LpKjOO/+uhjPwdhmFclTHgUo46x2tzGsoGWbiClpMoTLFfLITmDl/6f9icWiZE8HPpqWuWXQHOfVyokj77ue0ipBEeU1HHGA/EIQvzW80CMjHXvSpTzibTf6dAVAj+3vgOSRGa40d8L8ye0PoPKMW7fcRV7TcQp/CZMLOJzcnG8pFUw1DOsjzCr28Basd9JfSbqWQpvM/K65m1e4nbURXXHkYuCyrZ8duGZ75XiZGzLZmNNsbdmUBgR9ll6qOj8UloHAz2x7tI2iho4hxYczVEjXsq+cD35F96/XEGK/5MHF9RddGnSAoTVjd1/Kz49OsoZQAqQFsGgpttKLeMwAIRcBROEMQxpAlrqYO+KFXmU4mSzQA3oNmMfzzy1vmnNpFsZgYTx7DWikwSEv7GODAdQPUHPYX/2JEaOXIrqom9UPDTDRGq+Ln6Vruqy++LmwOtYaZ/DaM1scEdxS30Etsfz0DwZ/GX5Rw2J1eG9yNc/mGYw2BDpm3WnGMBzvQ=
  bucket: lgbtq.fm
  local-dir: build
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: h4mmzHWY15/bbwJCeIrfQAQ5yfKin7Mp/OmJmSnqyQzNg8Q5g6jBTikZOdO7Db8PbSIXPrpPHf7Y6dKt55yfoLCJXH8icJfstkD0ZTVTh9A2GC7JmcdBwWcRYwRbcnRU0qeMHEOKQRnsX4tzz8p8T8ZcyT9DdXK7n7QCRjMc9ELa54LpKjOO/+uhjPwdhmFclTHgUo46x2tzGsoGWbiClpMoTLFfLITmDl/6f9icWiZE8HPpqWuWXQHOfVyokj77ue0ipBEeU1HHGA/EIQvzW80CMjHXvSpTzibTf6dAVAj+3vgOSRGa40d8L8ye0PoPKMW7fcRV7TcQp/CZMLOJzcnG8pFUw1DOsjzCr28Basd9JfSbqWQpvM/K65m1e4nbURXXHkYuCyrZ8duGZ75XiZGzLZmNNsbdmUBgR9ll6qOj8UloHAz2x7tI2iho4hxYczVEjXsq+cD35F96/XEGK/5MHF9RddGnSAoTVjd1/Kz49OsoZQAqQFsGgpttKLeMwAIRcBROEMQxpAlrqYO+KFXmU4mSzQA3oNmMfzzy1vmnNpFsZgYTx7DWikwSEv7GODAdQPUHPYX/2JEaOXIrqom9UPDTDRGq+Ln6Vruqy++LmwOtYaZ/DaM1scEdxS30Etsfz0DwZ/GX5Rw2J1eG9yNc/mGYw2BDpm3WnGMBzvQ=
